language: rust
sudo: false

script:
  - cargo test
  - cargo doc --no-deps

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
  - secure: "d1VMo5q5vuotAOk48fXZL39kyfzGY2nlxmrUV8dTRGU+ulTf75wh3pGiCrqX6wj0r0zVUH//SJLSLmemgmb/bKDowHJp24IH50RcEzoOqItB7kfgMWlOFpCLu4bdYHhIHzZTAnI9MsuPjT2Y33FQlHV93zhgMWazgpulBNgnWIY="
